# Generated by Django 5.1.6 on 2025-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrupping', '0002_forml'),
    ]

    operations = [
        migrations.AddField(
            model_name='forml',
            name='form_type',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
